window.SKILLS = [
  {
    slug: "chapter-1-use-skills",
    title: "篇章一：把 Skills 用成一條順暢的工作流",
    group: "00 · 兩大主篇章",
    summary: "不是背指令，而是學會在每個工作節點做對判斷：先釐清、再驗證、再交付。",
    tags: ["實戰用法", "思考流程", "工作流"],
    body: [
      "## 先建立正確心智模型",
      "這套 Skills 不是 22 個互不相干的指令，而是一個工程工作的**導航系統**。真正要記住的不是名稱，而是每一刻你正在面對哪一種不確定性：需求不清楚、事實不確定、設計難以想像、工作太大、程式壞掉，或是需要驗收。Skill 的作用是替你把當下最容易犯的錯誤擋在門外。",
      "最實用的起點是這個自問：**我現在缺的是共識、證據、具體感、工作切分，還是品質保證？** 答案會自然導向下一個 Skill。",
      "## 一條完整的日常工作線",
      "### 1. 先別寫：把模糊想法變成共同理解",
      "當你說「我想做一個日文初學者練習網站」時，最危險的不是不知道怎麼寫，而是太早以為自己已經知道要寫什麼。此時用 `grill-with-docs`。它會一題一題問：使用者是誰、最小學習循環是什麼、答錯後怎麼回饋、第一版刻意不做什麼。每一題都在消除一種未來會返工的不確定性。",
      "思考方式不是「我要把需求問得很完整」，而是「有哪些決策彼此相依？哪一個決策不先定，後面都只是猜測？」例如是否需要帳號，會影響進度資料放本機還是雲端；而學習進度的定義，又會影響題目資料模型。一次只處理一個上游決策，才不會把使用者淹沒。",
      "### 2. 不靠想像就能回答的，先查證",
      "訪談裡要清楚分開 **fact** 與 **decision**。例如「目前專案使用什麼框架」「是否已有登入系統」是 fact，應由 agent 查看 repo 後回答；「第一版要不要登入」是 decision，必須交回使用者。把可查的事問使用者，會浪費對方的注意力；替使用者做價值決策，則會造成錯誤的自信。",
      "### 3. 紙上談不清楚，就做一個拋棄式原型",
      "若真正的問題是「這個五十音練習流程做起來順不順？」或「答題頁面應該長什麼樣」，切到 `prototype`。原型不是半成品，它是一個只回答**一個問題**的實驗。邏輯問題做小型互動 CLI；UI 問題做幾個截然不同、可切換的畫面。不要在這時追求 production 品質；你真正要保存的是結論與理由，不是原型程式。",
      "### 4. 共識已足夠時，把對話收斂成規格",
      "用 `to-spec` 時不要重新開需求會議。它的工作是把已經定下的東西整理成 Problem、Solution、User Stories、Implementation Decisions、Testing Decisions 和 Out of Scope。這一步最重要的思考是 **seam**：我要從哪個介面測到真實使用者行為？優先選最高、最接近使用者的 seam，而不是為了好寫測試就鑽進實作細節。",
      "### 5. 用垂直切片拆票，而不是按技術層分工",
      "接著 `to-tickets`。避免拆成「先做資料庫」「再做 API」「最後做畫面」；那會讓每張票都沒有可驗證價值。好的 ticket 是 tracer bullet：例如「使用者完成一題平假名選擇題後，立即看到對錯並更新今日答題數」。它可以穿過資料、規則和 UI，但仍能在一個 session 完成與驗證。",
      "思考 blocking edges 時，只標真正的依賴。若題目產生器尚不存在，答題流程可能被它阻擋；但單純因為你習慣先做 A 再做 B，不是依賴。清楚的 dependency graph 能讓多人或多個 session 安全平行。",
      "### 6. 實作時只推進一個可觀察行為",
      "`implement` 不是「一次把功能寫完」。它驅動 `tdd`，把工作切成 red → green → refactor：先寫一個會因使用者症狀而失敗的測試，確認它真的紅；再寫剛好足夠的程式讓它綠；最後在綠燈下整理設計。每一輪只做一個垂直切片，讓 feedback 永遠比猜測快。",
      "如果你開始想「這個架構以後可能需要……」，先問：目前這個測試要求它嗎？若沒有，先停。TDD 在這套流程中的價值，不是宗教式地先寫測試，而是用短迴圈逼迫每個設計決策都對一個可觀察行為負責。",
      "### 7. 壞掉時，先讓問題可重現，再猜原因",
      "遇到困難 Bug 就切 `diagnosing-bugs`。它最重要的規則是：沒有一條已實際執行、能抓住**此問題精確症狀**的 red-capable command，就不要進假設階段。先建 feedback loop，再最小化重現，提出至少三個可否證假設，用單一 probe 區分它們，最後才修正並補回歸測試。",
      "這個順序看似慢，實際上通常最快。很多除錯時間都浪費在沒有證據的閱讀與直覺修補；tight loop 把每一次嘗試變成可學習的實驗。",
      "### 8. 完成前做兩種不同的檢查",
      "`code-review` 將審查拆成 Standards 與 Spec。第一軸問「程式是否符合 repo 的品質規範？」；第二軸問「它是否真的完成當初承諾的需求？」兩者要分開，因為漂亮程式可以做錯功能，完整功能也可以留下危險設計。",
      "## 何時不要硬走主流程",
      "### 收到別人丟進來的 Issue",
      "先用 `triage`，不是直接實作。它要先確認問題是否成立、資訊是否足夠、需要誰決定，最後才變成 `ready-for-agent`。由 `to-tickets` 自己產生的票已經是 agent-ready，不要再 triage 一次。",
      "### 專案太大，連問題地圖都看不清楚",
      "用 `wayfinder`。它不是大型版 implement，而是用 decision tickets 建一張地圖；每個 session 只解一個問題，逐步把 fog of war 變成 frontier。地圖清楚後仍應回 `to-spec`，因為「知道答案」和「整理成可建置方案」是兩件事。",
      "### Context 快滿或要切分支實驗",
      "用 `handoff`。它是交接文件，不是流水帳：下一個 session 要知道目標、證據、已定決策、未定問題、重要檔案與下一步。`compact` 是留在同一對話的摘要；`handoff` 才是帶著可重建的上下文另開一條路。",
      "## 最短的實戰檢查表",
      "1. 現在的最大不確定性是什麼？\n2. 這是 fact 還是 decision？\n3. 是否需要把問題做得更具體才能回答？\n4. 這個工作能否在一個 session 內驗證？\n5. 下一步的完成條件是什麼？\n6. 如果這一步失敗，我靠哪一條 feedback loop 知道？\n7. 做完後，要如何確認品質與規格都沒有漏？",
      "## 與 22 個原始 Skills 的對照",
      "這篇是使用地圖。想知道某一步的精確行為，請回到側欄對應的原始導讀：`ask-matt` 看全圖；`grilling` 看訪談節奏；`to-spec`、`to-tickets`、`implement` 看交付鏈；`tdd`、`diagnosing-bugs`、`code-review` 看品質閉環；`wayfinder` 看大型探索。"
    ].join("\n\n"),
    files: [["ask-matt/SKILL.md", "整套流程的路由圖"], ["grilling/SKILL.md", "一次一題的決策協定"], ["tdd/SKILL.md", "實作迴圈"], ["diagnosing-bugs/SKILL.md", "除錯迴圈"]]
  },
  {
    slug: "chapter-2-writing-skills",
    title: "篇章二：Skill 為何這樣寫？從翻譯走到設計思維",
    group: "00 · 兩大主篇章",
    summary: "從觸發、資訊階層、完成條件與失敗模式，理解如何把工程判斷寫成可預測的 Agent 行為。",
    tags: ["Skill 寫作", "進階分析", "Predictability"],
    body: [
      "## 根本目標：不是讓輸出一樣，而是讓過程可預測",
      "Matt Pocock 在 `writing-great-skills` 裡的核心命題是：Skill 的工作，是在一個具隨機性的模型上，盡量約束出可預測的**過程**。這不代表每次輸出都要一樣；例如 brainstorming 本來就可以產生不同答案。但每次都應採取同一套合理程序：先查證、再決策；先重現、再假設；先選 seam、再寫測試。",
      "所以評估一份 Skill 的第一個問題不該是「它寫得詳細嗎？」而是：**它是否讓 agent 在關鍵岔路做出相同品質的判斷？**",
      "## 一、Invocation：先決定誰負責想起這份 Skill",
      "### Model-invoked 與 user-invoked 是一個成本取捨",
      "Model-invoked Skill 保留描述，讓 agent 能從使用者需求自動發現它；代價是 description 永遠佔用 context，形成 **context load**。User-invoked Skill 則只在使用者明確輸入時啟動，沒有 context load，但人類要記住何時使用它，形成 **cognitive load**。",
      "這正是為什麼 `tdd`、`diagnosing-bugs`、`research` 適合 model-invoked：使用者未必會說出 Skill 名稱，但任務明確需要它。反之，`to-spec`、`to-tickets`、`wayfinder` 是帶方向性的儀式性操作，讓人明確啟動反而更安全。當 user-invoked Skill 變多，就用 `ask-matt` 這種 router 降低人類記憶負擔。",
      "### Description 是機器可讀的入口，不是行銷文案",
      "好的 description 同時包含兩件事：它做什麼，以及哪些不同分支會觸發它。每個字都在花 context 預算，所以同義重述是浪費。`diagnosing-bugs` 的描述列出 broken、throwing、failing、slow，因為它們是不同的觸發表面；但「test-first」和「using TDD」若只指同一件事，就不必都寫。",
      "## 二、Information Hierarchy：把 agent 此刻必須知道的留在上面",
      "一份 Skill 的資訊有三層：**steps** 是現在要做的順序；檔內 **reference** 是需要時查閱的規則；外部 **reference** 則放到相關檔案，由 context pointer 指明何時讀取。這不是單純省 token，而是保護注意力：把每個分支都不需要的細節塞在最上面，agent 就更容易忽略真正的下一步。",
      "`prototype` 是好例子。主檔只要求先判斷問題屬於 logic 還是 UI；真正的 CLI 設計與多版本 UI 規則分別放在 `LOGIC.md` 和 `UI.md`。這叫 **progressive disclosure**：所有分支都需要的判斷留在主檔，只有特定分支需要的細節才透過明確 pointer 載入。",
      "### Context pointer 的文字比連結本身更重要",
      "「詳見 `LOGIC.md`」太弱，因為它沒有說 agent 何時必須讀。更可靠的寫法是：「當問題是『這個 state model 是否合理？』時，讀 `LOGIC.md`。」Pointer 本身就是一條觸發規則；如果重要資料藏在弱 pointer 後面，會造成執行變異。",
      "## 三、Steering：用 completion criteria 把建議變成門檻",
      "一般建議像「請徹底除錯」幾乎不能約束行為。`diagnosing-bugs` 改寫成具體 gate：你必須已經跑過一條單一 command，它會針對使用者精確症狀變紅，而且它必須 deterministic、快速、可由 agent 重跑。這樣 agent 知道什麼叫做完成 Phase 1，也知道在這之前不得跳去猜原因。",
      "這類 **completion criterion** 有兩個特徵：可檢查，以及在需要時具窮盡性。`code-review` 不只說「檢查品質」，而是要求從固定比較點審視 diff，並分別核對 Standards 與 Spec。`to-tickets` 不只說「拆小」，而是要求每張票可垂直驗證、標出 blocking edges。",
      "### Guardrail 為什麼要寫得硬",
      "模型和人類都容易追逐『快點結束』。這套 Skills 把常見捷徑變成明確禁令或正向替代：沒有 feedback loop 不假設；沒有使用者確認不實作；原型不升級為 production；衝突不因困難而 abort。硬護欄只應放在真的有危害的地方，否則會變成無效噪音。",
      "## 四、Leading words：用少量詞彙承載一整套行為",
      "這些 Skills 大量使用具有既有心智模型的詞：`tight` loop、`red`、`seam`、`tracer bullet`、`fog of war`、`frontier`、`deep module`。這些不是裝飾。好的 leading word 能把一大段說明折疊成一個 agent 已大致理解的概念，並在反覆出現時形成分散式定義。",
      "例如把 feedback loop 叫做 **tight**，同時暗示快速、明確、可重跑、低雜訊；把 bug loop 要求 **red-capable**，把模糊的『可測』變成二元判斷。寫自己的 Skill 時，應先找工作流程裡是否已有這種能壓縮思考的詞，而非每次都重新解釋原則。",
      "## 五、Granularity：何時該拆成另一份 Skill？",
      "拆得太細會增加 context load 或 cognitive load；拆得太粗則會讓一份 Skill 同時處理不相關分支，造成 sprawl。這套方法提供兩個拆分訊號：",
      "- **依 invocation 拆**：當有一個獨立 leading word，使用者會單獨提到，或其他 Skill 必須自主叫用它時，才值得成為 model-invoked Skill。\n- **依 sequence 拆**：當後面步驟太早出現在眼前，誘惑 agent 草率完成眼前一步時，把後續步驟切開。",
      "`grill-me` 與 `grilling` 的分工就是好示範：前者是使用者易記的入口，後者才是可重用的訪談 primitive。`prototype` 再依 logic/UI 分支把細節拆到 references。每一刀都有理由，不是為了看起來模組化。",
      "## 六、Pruning：好 Skill 靠刪除維持品質",
      "`writing-great-skills` 特別強調三種常見腐化：**duplication**（同一意思寫兩次）、**sediment**（過期文字一層層堆積）、**no-op**（模型本來就會做，寫了也不改變行為）。這些都會提高 token 與注意力成本，並意外把某個概念放得比它應有的更重要。",
      "實際修改時，可對每句問：刪掉這句會不會改變 agent 的行為？若不會，通常整句應刪除，不是換成更華麗的同義句。再問：這個意思是否已有 single source of truth？若有，改成 pointer，不要再複製。",
      "## 七、反向閱讀這套 Skills 的方法",
      "讀任何一份 `SKILL.md` 時，請用下面這張解剖表：\n1. **Trigger**：誰在什麼情況啟動它？\n2. **Inputs**：它假設哪些上下文與文件已存在？\n3. **Branches**：哪些條件讓流程分岔？\n4. **Steps**：現在必做的順序是什麼？\n5. **Evidence**：每一步靠什麼事實或回饋前進？\n6. **Completion criterion**：怎麼知道此步真的完成？\n7. **Guardrail**：最危險的捷徑是什麼？\n8. **Output contract**：最後留下什麼可供下一個 Skill 使用？\n9. **References**：哪些細節被刻意延後載入？為什麼？",
      "## 八、從模仿到自己寫：一個可重複的草稿法",
      "先不要從檔案格式開始。先拿一個反覆發生、且 agent 容易做錯的工作，例如「每次新增資料表前都確認 migration、索引、rollback 與資料保留」。寫下錯誤通常發生在哪裡；把它轉成一個正向流程；為每一步加可檢查的完成條件；只在真的必要處加入 guardrail；最後決定它要不要自動觸發，以及哪些細節應移到 reference 或 script。",
      "一份初稿的好壞，不在於長度，而在於 forward-test：讓 agent 用它完成一個真實任務，觀察它在哪個岔路漏讀、太早收工、誤觸發或重複做事。Skill 的成熟不是一次寫完，而是從這些失敗中反覆剪裁。",
      "## 結語：把經驗變成可交接的判斷力",
      "最好的 Skill 不會取代工程判斷；它把資深工程師平常隱性做的判斷順序、證據標準與停止條件，變成任何 agent 都能重複遵循的外部化知識。當你能看見這些設計選擇，你就不只是在翻譯指令，而是在學如何設計一套可靠的工作系統。"
    ].join("\n\n"),
    files: [["writing-great-skills/SKILL.md", "Predictability、Invocation 與資訊階層"], ["writing-great-skills/GLOSSARY.md", "完整的 Skill 設計詞彙"], ["ask-matt/SKILL.md", "Router Skill 的實例"]]
  },
  {
    slug: "ask-matt",
    title: "Ask Matt：整套工作流的導航器",
    group: "01 · 導航與設定",
    summary: "先判斷你身在什麼情境，再選擇最短、最合適的 Skill 流程。",
    tags: ["路由", "工作流", "Context 管理"],
    body: [
      "## 核心觀念",
      "你不需要背下每個 Skill。這篇把整套系統視為一張交通圖：大多數工作走在一條「想法到交付」的主線上，Bug、外部需求與大型模糊專案則從不同匝道匯入。",
      "## 主流程：從想法走到交付",
      "1. 有 codebase 時，用 **grill-with-docs** 訪談並同步建立 `CONTEXT.md` 與 ADR；沒有 codebase 時用 **grill-me**。",
      "2. 若某個問題無法只靠討論定案，先用 **handoff** 把上下文帶到新 session，再以 **prototype** 做拋棄式實驗，最後 handoff 回原始討論。",
      "3. 小工作可直接進 **implement**。跨多個 session 的工作先用 **to-spec** 整理規格，再用 **to-tickets** 拆成具有 blocking edges 的 tracer-bullet tickets。",
      "4. **implement** 內部以 **tdd** 推進，完成前再以 **code-review** 同時檢查 Standards 與 Spec。",
      "## 三條匝道",
      "- 收到未整理的 Bug 與需求：走 **triage**；由 `to-tickets` 產生的 tickets 已可直接交給 agent，不要重複 triage。",
      "- 難解、偶發或回歸型 Bug：走 **diagnosing-bugs**，先打造能穩定變紅的 feedback loop。",
      "- 大到一個 session 無法看清全貌的計畫：走 **wayfinder**，用 decision tickets 一步步驅散 fog of war；地圖清楚後仍要回到 `to-spec`。",
      "## Context 衛生",
      "從訪談到 tickets 盡量留在同一個 context window，確保推理連續；每個 implement ticket 則使用乾淨的新 session。快超過模型的 smart zone 時，用 **handoff** 保存上下文，不要在推理品質下降後硬撐。",
      "## 寫法拆解",
      "這是一個典型的 **router skill**：自己不執行細節，而是定義情境、分支條件、前置條件和交接點。好的 router 不是列清單，而是清楚回答「現在是哪一種情況、下一步去哪裡、什麼時候不要用」。"
    ].join("\n\n"),
    files: [["SKILL.md", "完整流程路由"], ["agents/openai.yaml", "Skill 顯示名稱與預設提示"]]
  },
  {
    slug: "setup-matt-pocock-skills",
    title: "Setup：為每個 Repo 建立共同設定",
    group: "01 · 導航與設定",
    summary: "先釐清 issue tracker、triage labels 與領域文件版型，讓後續 Skills 有一致的依據。",
    tags: ["初始化", "Issue Tracker", "文件慣例"],
    body: [
      "## 這個 Skill 解決什麼",
      "工程 Skills 需要知道 issue 放哪裡、triage 使用哪些 label、`CONTEXT.md` 與 ADR 放哪裡。Setup 不用硬編碼猜答案，而是先探索 repo、提出建議、取得確認，最後才寫入設定。",
      "## 五階段流程",
      "1. **探索**：檢查 Git remote、`.git/config`、`AGENTS.md`／`CLAUDE.md`、既有 domain docs、`.scratch/` 與 monorepo 訊號。",
      "2. **逐區確認**：一次只問一個決策。Issue tracker 預設跟隨 GitHub／GitLab remote，個人專案也可選 local Markdown。",
      "3. **設定 triage vocabulary**：若有安裝 triage，預設沿用 `needs-triage`、`needs-info`、`ready-for-agent`、`ready-for-human`、`wontfix`。",
      "4. **選擇 domain docs 版型**：一般 repo 預設 single-context；只有明確 monorepo 訊號才提出 multi-context。",
      "5. **先預覽再寫入**：展示即將加入的 `## Agent skills` 區塊與 `docs/agents/*.md` 草稿，讓使用者修改後才落盤。",
      "## 重要防護欄",
      "如果已有 `CLAUDE.md` 就更新它；否則更新既有 `AGENTS.md`。兩者都不存在時必須詢問，不可自行替使用者選擇。既有 `## Agent skills` 要原地更新，不要重複新增，更不能覆蓋周邊內容。",
      "## 寫法拆解",
      "這篇示範 **prompt-driven scaffold**：不是用固定 script 直接產檔，而是把「探索 → 推薦 → 決策 → 預覽 → 寫入」寫成受控流程。凡是設定會因 repo 狀態與團隊偏好而變動，都適合這種中等自由度寫法。"
    ].join("\n\n"),
    files: [["SKILL.md", "初始化主流程"], ["issue-tracker-github.md", "GitHub issue tracker 模板"], ["issue-tracker-gitlab.md", "GitLab 模板"], ["issue-tracker-local.md", "本機 Markdown 模板"], ["triage-labels.md", "Triage label 對照"], ["domain.md", "領域文件讀取規則"]]
  },
  {
    slug: "grill-me",
    title: "Grill Me：沒有 Codebase 的深度追問",
    group: "02 · 對齊與建模",
    summary: "對任何計畫或設計進行一題一題的嚴格訪談，但不在 repo 留下文件。",
    tags: ["訪談", "規劃", "User-invoked"],
    body: [
      "## 完整翻譯",
      "執行一次 **grilling** session。",
      "## 為什麼只有一句",
      "這是一個極薄的 **user-invoked wrapper**。它不複製底層訪談規則，而是把所有行為委派給 `grilling`，避免兩份 instructions 日後分歧。",
      "## 何時使用",
      "適合沒有 codebase 的規劃，例如課程設計、商業點子、活動流程或產品概念。若討論發生在既有 repo，且希望把詞彙與決策留下來，改用 `grill-with-docs`。",
      "## 寫法拆解",
      "可重用紀律放在 model-invoked primitive；使用者容易記住的入口則做成薄 wrapper。這是 Skill 組合設計中很值得學習的模式。"
    ].join("\n\n"),
    files: [["SKILL.md", "委派至 grilling 的極簡入口"]]
  },
  {
    slug: "grill-with-docs",
    title: "Grill with Docs：邊訪談、邊累積知識",
    group: "02 · 對齊與建模",
    summary: "把嚴格訪談與領域建模結合，讓共識同步落在 CONTEXT.md 與 ADR。",
    tags: ["訪談", "Domain Modeling", "ADR"],
    body: [
      "## 完整翻譯",
      "使用 **domain-modeling** Skill 執行一次 **grilling** session。",
      "## 與 Grill Me 的差異",
      "兩者使用同一套追問 primitive，但這個版本有 repo 狀態：它會建立並維護共同語言，把可逆的詞彙整理到 `CONTEXT.md`，把難以逆轉的重要決策寫成 ADR。",
      "## 設計價值",
      "需求訪談最常失敗的原因，是對話結束後共識沒有成為專案資產。這個 wrapper 把「問清楚」與「留下可供後續 agent 讀取的紀錄」綁在一起。",
      "## 寫法拆解",
      "短 Skill 也可以很有力量。關鍵在於組合兩個邊界清楚的底層能力，而不是重寫一篇龐大的流程。"
    ].join("\n\n"),
    files: [["SKILL.md", "組合 grilling 與 domain-modeling"]]
  },
  {
    slug: "grilling",
    title: "Grilling：一題一題走完決策樹",
    group: "02 · 對齊與建模",
    summary: "將模糊想法拆成決策分支，一次處理一個依賴，直到雙方建立共同理解。",
    tags: ["決策樹", "HITL", "Shared Understanding"],
    body: [
      "## 工作規則",
      "針對計畫、決策或想法的每個面向持續追問，沿著 decision tree 的各個分支前進，逐一解開決策間的依賴。每一題都要附上 agent 的建議答案。",
      "## 一次只能問一題",
      "每次提出一個問題並等待回覆。一次丟出多題會讓使用者不知從何回答，也讓決策的依賴關係變得混亂。",
      "## 事實與決策要分開",
      "可從 filesystem、工具或環境查到的 **fact**，agent 應自行查證，不要把研究工作推回使用者；但真正的 **decision** 屬於使用者，必須逐題提出並等待回答。",
      "## 停止條件",
      "在使用者確認已達成共同理解前，不可開始執行方案。這條規則防止 agent 一邊訪談一邊偷跑實作。",
      "## 寫法拆解",
      "這篇很短，卻把互動協定定義得很精準：問題粒度、等待時機、fact/decision 邊界與 action gate 都明確。對 HITL Skill 而言，互動節奏本身就是核心產品。"
    ].join("\n\n"),
    files: [["SKILL.md", "拷問式訪談 primitive"]]
  },
  {
    slug: "domain-modeling",
    title: "Domain Modeling：建立專案共同語言",
    group: "02 · 對齊與建模",
    summary: "主動挑戰模糊、重疊或被誤用的詞彙，並把領域知識與重大決策寫回專案。",
    tags: ["Ubiquitous Language", "CONTEXT.md", "ADR"],
    body: [
      "## 目標",
      "Domain model 不是資料庫 schema，而是團隊用來理解問題空間的共同語言。Agent 要主動辨識同義詞、過度模糊的名稱，以及一個詞同時代表多種概念的情況。",
      "## 兩種文件",
      "- `CONTEXT.md`：可持續演進的 glossary，記錄術語、定義、關係與非顯而易見的限制。",
      "- ADR：記錄難以逆轉、會影響未來設計的重要決策，包括背景、選項、決定與後果。",
      "## 執行方法",
      "讀取相關 context 與既有 ADR；在對話或程式碼中遇到用詞衝突時，提出更精準的候選語彙；用 edge cases 壓測定義；取得使用者確認後才更新文件。避免把實作細節、暫時狀態與容易從 code 看出的事塞進 glossary。",
      "## 寫法拆解",
      "這是一個 **vocabulary layer**，可被其他 Skill 隱性叫用。它不擁有完整交付流程，而是擁有一套跨流程都一致的詞彙紀律，讓各 Skill 不必各自發明 domain modeling 規則。"
    ].join("\n\n"),
    files: [["SKILL.md", "領域建模流程"], ["CONTEXT-FORMAT.md", "共同語言文件格式"], ["ADR-FORMAT.md", "架構決策紀錄格式"]]
  },
  {
    slug: "to-spec",
    title: "To Spec：把既有共識收斂成規格",
    group: "03 · 規格與任務",
    summary: "不重新訪談，而是把目前對話與 codebase 理解整理為可交付的 PRD／Spec。",
    tags: ["PRD", "User Stories", "Testing Seams"],
    body: [
      "## 重要前提",
      "這個 Skill **不能重新訪談使用者**。它只負責綜合目前對話與已取得的 codebase 知識；如果資訊不足，代表前面的 grilling 還沒有完成。",
      "## 三步流程",
      "1. 探索 repo 現況，沿用 domain glossary 的用語並遵守相關 ADR。",
      "2. 先規劃測試 seam：優先使用既有 seam，選可觀察到完整外部行為的最高層級；seam 越少越好，理想狀況只有一個。這一步要與使用者核對。",
      "3. 依模板撰寫 spec，發布到已設定的 issue tracker，並套用 `ready-for-agent`，不需再次 triage。",
      "## Spec 必備章節",
      "- Problem Statement：從使用者角度描述問題。",
      "- Solution：從使用者角度描述解法。",
      "- User Stories：完整、編號，使用「身為…我想要…以便…」格式。",
      "- Implementation Decisions：模組、介面、架構、schema、API contract 與互動決定；避免容易過時的檔案路徑與程式碼。",
      "- Testing Decisions：好測試的定義、測試模組與 repo 中的 prior art。",
      "- Out of Scope 與 Further Notes。",
      "## 寫法拆解",
      "這篇清楚區分 **探索、需要確認的設計決策、以及不該再問的需求訪談**。Skill 若能明講禁止事項，通常比只寫理想流程更可靠。"
    ].join("\n\n"),
    files: [["SKILL.md", "規格生成流程與模板"]]
  },
  {
    slug: "to-tickets",
    title: "To Tickets：用 Tracer Bullet 拆工作",
    group: "03 · 規格與任務",
    summary: "把規格拆成可獨立交付、能垂直驗證，而且明確標示阻擋關係的 tickets。",
    tags: ["Tracer Bullet", "Blocking Edges", "Issue Tracker"],
    body: [
      "## 不按技術層水平切割",
      "不要先做 database ticket、再做 API ticket、最後做 UI ticket。每張 ticket 應是一條很細但可運作的垂直切片，穿過必要層級並產生可觀察價值；這就是 tracer bullet。",
      "## Ticket 的尺寸",
      "每張票應能在一個乾淨 context window 內完成。它要提供足夠背景、驗收行為、測試 seam 與相關決策，但不能塞入整份 spec。Agent 應從 blockers-first 開始，完成一張後清理 context，再進下一張。",
      "## Blocking edges",
      "Ticket 必須宣告真正的依賴，而不是僅靠編號暗示順序。使用 real tracker 時建立原生 blocking relationship；使用 local tracker 時，每張票各自存檔並用文字記錄依賴。",
      "## 好的拆分檢查",
      "- 每張票完成後是否能驗證一個真實行為？",
      "- 是否能單獨 review 與 commit？",
      "- 是否把架構風險或不確定性放在早期切片？",
      "- 是否避免多張票同時修改同一模糊 seam？",
      "## 寫法拆解",
      "這個 Skill 將抽象的「拆小任務」具體化成拆分原則、ticket contract、依賴圖與 tracker-specific 實作，是 **概念 + deterministic constraints** 的混合寫法。"
    ].join("\n\n"),
    files: [["SKILL.md", "Ticket 拆分與發布規則"]]
  },
  {
    slug: "wayfinder",
    title: "Wayfinder：在大型模糊專案中找路",
    group: "03 · 規格與任務",
    summary: "用決策 tickets、frontier 與 fog of war 管理一個 session 根本裝不下的大型探索。",
    tags: ["Decision Map", "Fog of War", "Multi-session"],
    body: [
      "## 它產生決策，不產生功能",
      "Wayfinder 適用於目的地存在、但路線還看不清楚的巨型工作。每張 ticket 解開一個決策或調查，不直接交付最終產品；地圖清楚後，還要回到 `to-spec` 與 `to-tickets`。",
      "## 地圖結構",
      "- Destination：到達什麼狀態才算完成。",
      "- Notes：tracker、領域文件與使用規則。",
      "- Decisions so far：已關閉 tickets 的一行摘要與連結。",
      "- Not yet specified：知道將來要處理、但目前連問題都還說不精準的 fog。",
      "- Out of scope：明確超出 destination 的工作，永遠不會從 fog 升級。",
      "## Frontier",
      "Open、unblocked、unclaimed 的 child tickets 形成 frontier，也就是現在可以著手的已知邊界。Session 開始前先用 assignee claim ticket，避免多個 agent 撞在一起。",
      "## 四種 Ticket",
      "- Research（AFK）：讀 primary sources，交給 research agent。",
      "- Prototype（HITL）：做低成本具體物，讓人能針對外觀或行為回饋。",
      "- Grilling（HITL）：一次一題的決策訪談，也是預設類型。",
      "- Task（HITL 或 AFK）：為了讓後續決策成為可能而必須先完成的操作。",
      "## 一個 Session 只解一張",
      "除了可平行的 research，單一 session 絕不解多張 ticket。解題後以 resolution comment 記錄答案、關閉 issue、更新 Decisions-so-far，再把新看清楚的 fog 升級為 tickets。",
      "## 寫法拆解",
      "這篇用一套嚴謹的狀態機語彙控制跨 session 協作。長 Skill 的關鍵不是詳盡，而是建立穩定的 nouns、狀態轉移與不變條件。"
    ].join("\n\n"),
    files: [["SKILL.md", "Decision map、ticket types 與工作模式"]]
  },
  {
    slug: "triage",
    title: "Triage：把外來 Issue 整理成可行動狀態",
    group: "03 · 規格與任務",
    summary: "讓未整理的 Bug、需求與外部 PR 依角色狀態機流動，最後產出 agent-ready brief。",
    tags: ["Issue Triage", "State Machine", "Agent Brief"],
    body: [
      "## 適用範圍",
      "Triage 只處理外部進來、尚未整理的 issue：Bug report、feature request 或原始 PR。由 `to-tickets` 產生的票已具備 agent-ready 資訊，不要再次 triage。",
      "## 五個角色狀態",
      "- `needs-triage`：尚未分類。",
      "- `needs-info`：缺少重現、期望行為或必要背景，等待回報者補充。",
      "- `ready-for-agent`：範圍清楚、資訊完整，可由 agent 執行。",
      "- `ready-for-human`：需要產品、權限、政策或主觀判斷。",
      "- `wontfix`：明確不做，需說明原因。",
      "## Triage 的工作",
      "先分類並驗證 issue 是否成立；能從 repo 或工具查到的資訊自行找，不要要求回報者代查；必要時用 grilling 一次追一個缺口；最後撰寫 agent brief，包含問題、重現、期望行為、驗收、風險、測試 seam 與 out-of-scope。",
      "## 外部 PR",
      "PR 是否進入 triage queue 由 setup 文件的 flag 決定。不要在 Skill 中硬猜團隊是否接受外部 PR 作為需求入口。",
      "## 寫法拆解",
      "這篇把 labels 當成 **工作角色**，不是單純分類標籤。用狀態機限制每一步輸入、輸出與負責者，能防止 agent 在資訊不足時直接開工。"
    ].join("\n\n"),
    files: [["SKILL.md", "Triage 狀態機"], ["AGENT-BRIEF.md", "Agent-ready issue 模板"], ["OUT-OF-SCOPE.md", "不處理事項與判斷方式"]]
  },
  {
    slug: "implement",
    title: "Implement：從 Ticket 推進到可提交成果",
    group: "04 · 實作與驗證",
    summary: "以規格或 tickets 為依據實作，透過 TDD 推進，最後用雙軸 Review 關門。",
    tags: ["實作", "TDD", "Code Review"],
    body: [
      "## 完整流程",
      "根據 spec 或 ticket 實作工作。在事先約定的測試 seams 上使用 **tdd**，以一個個 red-green-refactor 垂直切片推進。",
      "## 完成前",
      "不要只因測試變綠就宣告完成。結尾必須執行 **code-review**，同時檢查 repo Standards 與原始 Spec，修正發現後才進入 commit。",
      "## Context 原則",
      "多 ticket 工作中，每張 ticket 用新的乾淨 session，從 ticket 本身重建必要脈絡。這能避免上一張票的探索、假設和臨時細節污染下一張。",
      "## 寫法拆解",
      "Implement 也是薄 orchestration skill：它不重複 TDD 與 review 細節，而是定義兩者在交付生命週期中的位置。"
    ].join("\n\n"),
    files: [["SKILL.md", "實作編排入口"]]
  },
  {
    slug: "tdd",
    title: "TDD：以 Red–Green–Refactor 垂直前進",
    group: "04 · 實作與驗證",
    summary: "先讓外部行為的測試失敗，再以最小變更通過，最後在綠燈下改善設計。",
    tags: ["Red-Green-Refactor", "Integration Tests", "Mocking"],
    body: [
      "## Red",
      "先選能觀察真實行為的最高 seam，寫一個聚焦於外部行為的失敗測試，並親眼確認它因為預期原因而紅。若測試一開始就綠、因 typo 爆掉，或只驗證 mock 呼叫，都不算有效 Red。",
      "## Green",
      "只寫足以通過目前測試的最小 production change。不要同時實作未被測試要求的抽象、泛化與預測性功能。每個切片都應是可運作的垂直行為。",
      "## Refactor",
      "測試保持綠燈時，改善命名、消除重複、深化 module 或調整 seam。重構不能改變行為；每個小步都要重跑測試。",
      "## 測試哲學",
      "優先 integration-style 測試：透過 public interface 驗證結果，不測 implementation details。好的測試能在內部重構後保持不變，且失敗時清楚指出哪個使用者行為壞掉。",
      "## Mocking 原則",
      "Mock 只放在真正的系統邊界，例如網路、時間、隨機或外部服務。不要 mock 自己的 domain code，也不要讓測試退化成「某個函式被呼叫幾次」。",
      "## 寫法拆解",
      "主檔保留循環與決策規則，把 tests 與 mocking 的深入細節拆成 references，正是漸進式揭露：觸發時先讀核心，需要時才載入延伸知識。"
    ].join("\n\n"),
    files: [["SKILL.md", "TDD 主循環"], ["tests.md", "測試品質與 seam"], ["mocking.md", "Mock 使用原則"]]
  },
  {
    slug: "diagnosing-bugs",
    title: "Diagnosing Bugs：先打造會變紅的 Feedback Loop",
    group: "04 · 實作與驗證",
    summary: "用可重現、可縮小、可否證的診斷循環處理頑固 Bug 與效能回歸。",
    tags: ["Debugging", "Feedback Loop", "Regression Test"],
    body: [
      "## Phase 1：建立 Feedback Loop",
      "這就是整個 Skill 的核心。先得到一個已實際執行、能針對使用者確切症狀變紅的單一 command。可用 failing test、HTTP script、CLI fixture、headless browser、trace replay、throwaway harness、fuzz loop、git bisect、差分比較或最後手段的 HITL script。",
      "Loop 必須 **red-capable、deterministic、fast、agent-runnable**。沒有這個 command，不可跳去猜原因。",
      "## Phase 2：重現並最小化",
      "確認抓到的是使用者描述的同一個 Bug。接著一次移除一個 input、caller、config、data 或 step，每次重跑；直到剩下的每一項都是 failure 的必要條件。",
      "## Phase 3：提出可否證假設",
      "先列出 3 個以上並排序。每個假設都要用「如果 X 是原因，改變 Y 應讓 Bug 消失／惡化」表達 prediction。先讓使用者看到排序，但使用者不在線時可繼續。",
      "## Phase 4：Instrumentation",
      "每個 probe 只對應一個 prediction，一次改一個變數。優先 debugger／REPL，其次是邊界上的 targeted logs。所有暫時 log 使用唯一 `[DEBUG-xxxx]` 前綴；效能問題改用 baseline、profiler、query plan 與 bisect。",
      "## Phase 5–6：修正、回歸測試與事後檢討",
      "在正確 seam 先把最小重現轉成 failing regression test，再修正並重跑原始 loop。若沒有可忠實重現 Bug 的 seam，這本身就是架構發現。最後移除 instrumentation、刪除 throwaway artifacts、記錄真正原因，並評估是否交給 architecture improvement。",
      "## 寫法拆解",
      "這篇用 phase gates 與 completion checklist 阻止 agent 走捷徑。對高風險流程，明確寫出「沒有 X 就不得進下一階段」比一般建議更有效。"
    ].join("\n\n"),
    files: [["SKILL.md", "六階段診斷循環"], ["scripts/hitl-loop.template.sh", "需要人類操作時的結構化迴圈"]]
  },
  {
    slug: "code-review",
    title: "Code Review：標準與規格的雙軸審查",
    group: "04 · 實作與驗證",
    summary: "從固定比較點審查 diff，讓程式品質與需求忠實度互不污染。",
    tags: ["Standards", "Spec", "Parallel Review"],
    body: [
      "## 固定審查範圍",
      "先確定比較起點：commit、branch、tag 或 merge-base。審查的是從固定點到目前狀態的 diff，而不是整個 codebase 的泛泛評論。",
      "## Axis A：Standards",
      "依 repo 明文規範、AGENTS 指引、測試慣例與 Fowler code smells 檢查品質。重點是正確性、可維護性、命名、重複、耦合、錯誤處理與測試，不以個人偏好取代專案標準。",
      "## Axis B：Spec",
      "獨立讀取原始 issue、PRD 或 ticket，逐項核對實作是否忠實完成需求、是否漏掉 user story、是否做了 out-of-scope 內容，以及測試是否覆蓋約定行為。",
      "## 為什麼要分開",
      "兩個軸使用平行 sub-agents，避免「程式寫得漂亮」掩蓋做錯需求，也避免「功能看起來完成」掩蓋嚴重設計問題。最後由主 agent 合併、去重、排序。",
      "## 報告原則",
      "只報可行動、具證據的 findings；標示檔案與行號、影響、修正方向和優先度。沒有問題就明確說沒有，不為了顯得有做事而製造 nit。",
      "## 寫法拆解",
      "這是 **independent evaluators** 模式：把容易互相錨定的判準拆成隔離工作，再由上層彙整。適合需要不同觀點且可平行驗證的審查型 Skill。"
    ].join("\n\n"),
    files: [["SKILL.md", "雙軸審查與報告格式"]]
  },
  {
    slug: "prototype",
    title: "Prototype：用拋棄式程式回答一個問題",
    group: "05 · 設計與架構",
    summary: "依問題選擇 logic 或 UI 分支，快速提高討論解析度，保留答案而非原型。",
    tags: ["Throwaway Code", "Logic", "UI Variants"],
    body: [
      "## 問題決定原型形狀",
      "- 「這個 logic／state model 合理嗎？」走 `LOGIC.md`：做小型互動 CLI，推動 state machine 穿過紙上難以判斷的 cases。",
      "- 「這個 UI 應該長什麼樣？」走 `UI.md`：在單一路由做數個差異極大的版本，用 URL parameter 與浮動切換列比較。",
      "## 共同規則",
      "1. 從第一天就標示為 throwaway，放在接近實際使用位置但名稱清楚。",
      "2. 只需要一個簡單 command 就能啟動。",
      "3. 預設不做 persistence；state 存在 memory。",
      "4. 不做 production polish、完整 error handling、抽象與 tests。",
      "5. 每次 action 或 variant 切換都呈現完整相關 state。",
      "6. 驗證完成後把決策併入正式程式；原型放在 main 之外的 throwaway branch，並在 issue 留 context pointer。",
      "## 核心心法",
      "原型的產出不是 code，而是答案。真正要保存的是「它回答了什麼問題、得到什麼 verdict」，不是把快速實驗偷偷升級成 production。",
      "## 寫法拆解",
      "主檔先做 branch selection，再把完全不同的執行細節放到兩份 reference。這是多變體 Skill 最清晰的導航結構。"
    ].join("\n\n"),
    files: [["SKILL.md", "分支選擇與共通規則"], ["LOGIC.md", "互動式邏輯原型"], ["UI.md", "多版本 UI 原型"]]
  },
  {
    slug: "codebase-design",
    title: "Codebase Design：打造深模組與乾淨 Seam",
    group: "05 · 設計與架構",
    summary: "用一致詞彙討論 module depth、interface、leverage、locality 與可測試邊界。",
    tags: ["Deep Modules", "Seams", "Locality"],
    body: [
      "## 深模組",
      "好的 module 在小而穩定的 interface 後面隱藏大量行為與複雜度，也就是 **deep**。Shallow module 則讓呼叫者仍需理解大量內部細節，增加整體認知負擔。",
      "## Seam",
      "Seam 是可在不改變整體系統下替換、測試或重新組合行為的邊界。測試應盡量從最高、最能代表真實使用方式的 seam 進入；太低的 seam 會把 implementation details 固化。",
      "## 設計判準",
      "- Interface 是否比 implementation 簡單很多？",
      "- 變更是否集中在一個 locality，而不是散落多層？",
      "- 一個新行為能否透過少數高 leverage 變更完成？",
      "- Domain concepts 是否落在正確 module，而非由 callers 重複拼裝？",
      "## Design It Twice",
      "對重要 interface 至少設計兩個明顯不同的方案，再比較 complexity 藏在哪裡、誰承擔成本、哪個更容易測試與演進。第一個可行答案常只是沿用現狀。",
      "## 寫法拆解",
      "這是一個 vocabulary Skill：提供跨 TDD、prototype、架構改善都能共用的設計語言。穩定詞彙會讓其他 Skills 更短、更一致。"
    ].join("\n\n"),
    files: [["SKILL.md", "深模組設計詞彙"], ["DEEPENING.md", "深化模組的方法"], ["DESIGN-IT-TWICE.md", "至少提出兩種設計"]]
  },
  {
    slug: "improve-codebase-architecture",
    title: "Improve Architecture：尋找模組深化機會",
    group: "05 · 設計與架構",
    summary: "掃描 codebase 中反覆外洩的複雜度，產出視覺報告，再針對選中的機會深入訪談。",
    tags: ["Architecture", "Deepening", "HTML Report"],
    body: [
      "## 目標不是大重寫",
      "這個 Skill 尋找 **deepening opportunities**：多個 caller 重複知道同一組細節、薄 wrapper 沒隱藏複雜度、重要規則散落、測試找不到合適 seam。它提出的是可深化模組的候選，不是全面翻新。",
      "## 掃描方法",
      "讀取 domain docs 與相關程式，從重複、feature envy、shotgun surgery、primitive obsession、長參數列、case 分散等跡象找出「哪個知識應被一個 interface 擁有」。",
      "## HTML 視覺報告",
      "候選以可開啟的 HTML 呈現，包括現況、複雜度如何外洩、建議的新 seam、預期 leverage、風險與證據。使用者先瀏覽全貌，再選擇值得深入的一項。",
      "## 選中之後",
      "用 grilling 與 codebase-design 深入，不直接偷偷重構。把候選轉成清楚想法後，匯入主流程的 `grill-with-docs → to-spec → implement`。",
      "## 寫法拆解",
      "這篇把分析結果規定為視覺 artifact，讓人類能有效選擇方向。Skill 的 output contract 不一定是文字；當比較多個候選時，HTML 可以比 terminal 報告更可用。"
    ].join("\n\n"),
    files: [["SKILL.md", "架構掃描與互動流程"], ["HTML-REPORT.md", "視覺報告的內容與版面規格"]]
  },
  {
    slug: "research",
    title: "Research：以 Primary Sources 進行背景調查",
    group: "06 · 維運與知識",
    summary: "把查資料交給背景 agent，要求高可信來源，最後在 repo 留下可引用的研究文件。",
    tags: ["Primary Sources", "Citations", "Background Agent"],
    body: [
      "## 任務",
      "針對文件、API 或技術事實進行閱讀調查。優先使用官方文件、標準、原始論文、規格與專案 source code，不以搜尋摘要或二手文章作為最後依據。",
      "## 執行方式",
      "研究適合交給 background agent，讓主 session 繼續工作。研究者要界定問題、列出已知與未知、查閱高信任來源、區分來源明示的 fact 與自己的 inference。",
      "## 產出",
      "在 repo 建立有清楚檔名的 Markdown，包含問題、結論、證據、未確定事項、日期與貼近 claim 的 citations。研究檔是下一階段 `grill-with-docs` 的輸入，不取代產品決策。",
      "## 寫法拆解",
      "這篇定義的是 evidence discipline：來源階級、fact/inference 邊界與可追溯 artifact。Research Skill 的品質主要由來源政策與交付格式決定。"
    ].join("\n\n"),
    files: [["SKILL.md", "研究流程與引用規則"]]
  },
  {
    slug: "resolving-merge-conflicts",
    title: "Resolving Merge Conflicts：按意圖解衝突",
    group: "06 · 維運與知識",
    summary: "逐個 conflict hunk 回溯兩邊的原始意圖，完成 merge／rebase，而不是直接 abort。",
    tags: ["Git", "Merge", "Intent"],
    body: [
      "## 核心原則",
      "Conflict 不是選 ours 或 theirs 的文字題，而是兩組意圖同時落在相同位置。先讀每一邊的 commit、issue、PR 或測試，理解它各自想保留的行為。",
      "## 流程",
      "確認目前是 merge 還是 rebase；列出 conflicted files；逐 hunk 比較 base、ours、theirs；依意圖合成結果；執行相關 tests；stage 已解檔案；持續完成原本的 Git 操作。",
      "## 禁止事項",
      "不可因為衝突困難就 `--abort`，不可整檔接受某一邊，也不可刪除不理解的測試。若兩邊意圖真的互斥，提出精確決策點給使用者。",
      "## 寫法拆解",
      "高風險操作適合低自由度 Skill：順序、證據來源、禁止捷徑與完成條件都應明寫。"
    ].join("\n\n"),
    files: [["SKILL.md", "逐 hunk 解衝突流程"]]
  },
  {
    slug: "handoff",
    title: "Handoff：把一個 Session 安全交給下一個",
    group: "06 · 維運與知識",
    summary: "將目前對話壓縮成自足文件，讓新的 agent session 不需讀完整歷史也能接手。",
    tags: ["Context", "Session", "Knowledge Transfer"],
    body: [
      "## 何時用",
      "Context 快滿、要分支去做 prototype、要交給另一位 agent，或需要新的乾淨 session 時使用。Handoff 是跨 context window 的橋；內建 compact 則是在同一對話繼續。",
      "## 文件要自足",
      "記錄目標、目前狀態、已做決策與理由、重要檔案、執行過的 commands 與結果、未完成事項、風險、下一步，以及任何不可重新推導的使用者偏好。",
      "## 不要做什麼",
      "不要寫成流水帳，也不要只說「請看前文」。刪除無用探索細節，但保留會影響下一步判斷的證據與 context pointers。",
      "## 寫法拆解",
      "Handoff 的 output 不是摘要，而是 **continuation contract**。寫 Skill 時應用接手者角度檢查：若看不到原對話，他是否仍能安全前進？"
    ].join("\n\n"),
    files: [["SKILL.md", "跨 session 交接規格"]]
  },
  {
    slug: "teach",
    title: "Teach：把資料夾變成多 Session 學習空間",
    group: "06 · 維運與知識",
    summary: "以 mission、學習紀錄、glossary 與 resources 管理長期學習，而不是一次講完。",
    tags: ["教學", "Stateful Learning", "多 Session"],
    body: [
      "## 教學不是資訊傾倒",
      "先了解學習者的目標、背景、可投入時間與成功標準，再設計一個可驗證的 mission。每次 session 只推進合適份量，透過提問、練習與回饋檢查真正理解。",
      "## 四種持久文件",
      "- Mission：學習目標、範圍、成功條件與路線。",
      "- Learning Record：每次 session 做了什麼、掌握什麼、卡在哪裡、下一步是什麼。",
      "- Glossary：逐步穩定概念語彙，避免每次重新解釋。",
      "- Resources：經過篩選的參考資料與使用時機。",
      "## 教學節奏",
      "從 learner 已知處開始；一次引入少數新概念；先讓對方預測，再示範；安排能暴露誤解的練習；用 teach-back 驗證，而不是問「懂了嗎」。",
      "## 寫法拆解",
      "這個 Skill 將 memory 外部化成結構化 artifacts，因此能跨 session 延續。凡是長期工作流，都應明確定義狀態存在哪裡、何時更新、下一個 session 如何重建上下文。"
    ].join("\n\n"),
    files: [["SKILL.md", "多 session 教學流程"], ["MISSION-FORMAT.md", "學習任務格式"], ["LEARNING-RECORD-FORMAT.md", "學習紀錄格式"], ["GLOSSARY-FORMAT.md", "術語表格式"], ["RESOURCES-FORMAT.md", "資源清單格式"]]
  },
  {
    slug: "writing-great-skills",
    title: "Writing Great Skills：如何寫出可靠的 Skill",
    group: "07 · Skill 寫作",
    summary: "從 vocabulary、trigger、自由度、組合與漸進式揭露，理解 Skill 為何可預測。",
    tags: ["Skill Design", "Progressive Disclosure", "Triggers"],
    body: [
      "## Skill 是什麼",
      "Skill 是一套可重複使用的程序性知識：它告訴 agent 何時採用某種工作方式、如何做決策、需要讀哪些 references、要產出什麼，以及哪些捷徑禁止走。",
      "## Description 是觸發器",
      "`name` 與 `description` 會在完整本文載入前先被看到。Description 必須同時說清楚「它做什麼」與「什麼情境該用」，不要把觸發條件只藏在 body。",
      "## 自由度要與風險匹配",
      "- 高自由度：多種方案都可接受，使用原則與 heuristics。",
      "- 中自由度：有偏好流程，但會依環境變化，使用步驟、判斷表或 parameterized script。",
      "- 低自由度：脆弱或高風險操作，規定命令、順序、guardrails 與 completion checks。",
      "## 漸進式揭露",
      "主 `SKILL.md` 保留核心流程與導航；詳細範例、schema、provider-specific 作法放 references；重複且需 deterministic 的操作放 scripts；輸出會使用的模板或素材放 assets。不要把同一知識重複寫在多處。",
      "## 組合優於複製",
      "用薄 wrapper 提供容易記住的入口，把共用紀律放在 model-invoked primitive。Router 負責選路，vocabulary layer 負責共同語言，orchestrator 負責安排各 Skill 的生命週期位置。",
      "## 指令語氣與不變條件",
      "使用祈使語氣，寫出可觀察完成條件。重要限制要用明確 gate，例如「沒有 red-capable command 就不可進 Phase 2」，不要只寫成軟性提醒。",
      "## 避免的壞味道",
      "- 把模型本來就知道的常識寫得很長。",
      "- Trigger 過寬，導致每個任務都誤觸發。",
      "- 沒有停止條件，流程無限延伸。",
      "- 一個 Skill 同時擁有太多互不相關的工作。",
      "- Reference 深層互相連結，agent 找不到真正入口。",
      "- 只描述理想路徑，沒有失敗模式與禁止捷徑。",
      "## 建議的學習方法",
      "挑本手冊任一篇，標出五個元素：trigger、inputs、decision points、outputs、guardrails。接著問：哪些內容可移到 reference？哪些步驟需要 script？最後用一個真實任務 forward-test，觀察 agent 在哪裡誤解，再修改 Skill。"
    ].join("\n\n"),
    files: [["SKILL.md", "Skill 寫作原則"], ["GLOSSARY.md", "Skill 設計詞彙全集"]]
  }
];
